spring.application.name=backend

# Server Configuration

server.port=10000

# ================= DATABASE CONFIG (RENDER POSTGRESQL) =================

spring.datasource.url=jdbc:postgresql://dpg-d759rua4d50c73e8kotg-a:5432/hospitaldatabase_7drz
spring.datasource.username=hospitaldatabase_7drz_user
spring.datasource.password=lsrijqr59zkfkHnAyFF1pgtDxhBPBLnk

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

# ================= JPA CONFIG =================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ================= JWT CONFIG =================

app.jwt.secret=test-secret-key-with-minimum-32-characters-12345
app.jwt.expiration-ms=86400000

# ================= FILE UPLOAD =================

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=./uploads

# ================= ACTUATOR =================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
